apiVersion: v1
kind: ServiceAccount
metadata:
  name: geo-climate-sa
  namespace: geo-climate
  labels:
    app: geo-climate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: geo-climate-role
  namespace: geo-climate
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: geo-climate-rolebinding
  namespace: geo-climate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: geo-climate-role
subjects:
- kind: ServiceAccount
  name: geo-climate-sa
  namespace: geo-climate
